CREATE VIEW BritishShips
AS
	SELECT CLASSES.CLASS, CLASSES.TYPE, CLASSES.NUMGUNS, CLASSES.BORE, CLASSES.DISPLACEMENT, SHIPS.LAUNCHED
	FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
	WHERE CLASSES.COUNTRY = 'Gt.Britain'

GO

ALTER VIEW BritishShips
AS
	SELECT CLASSES.NUMGUNS, CLASSES.DISPLACEMENT
	FROM CLASSES LEFT JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
	WHERE CLASSES.COUNTRY = 'Gt.Britain' AND CLASSES.TYPE = 'bb' AND SHIPS.LAUNCHED < 1919

GO

CREATE VIEW SunkShips
AS
	SELECT SHIP, BATTLE
	FROM OUTCOMES
	WHERE RESULT = 'sunk'
	
GO

CREATE VIEW ClassesWithAtLeast9Guns
AS
	SELECT *
	FROM CLASSES
	WHERE NUMGUNS >= 9
WITH CHECK OPTION;

GO

CREATE VIEW BattlesWith3Ships
AS
	SELECT OUTCOMES.BATTLE
	FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
				  JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
	WHERE CLASSES.NUMGUNS < 9 AND OUTCOMES.BATTLE IN ( SELECT BATTLE
													   FROM OUTCOMES
													   WHERE RESULT = 'sunk' )
	GROUP BY OUTCOMES.BATTLE
	HAVING COUNT(*) >= 2;

GO

SELECT *
FROM BritishShips;

SELECT *
FROM SunkShips;

SELECT *
FROM ClassesWithAtLeast9Guns;

SELECT *
FROM BattlesWith3Ships;

DROP VIEW BritishShips;
DROP VIEW SunkShips;
DROP VIEW ClassesWithAtLeast9Guns;
DROP VIEW BattlesWith3Ships;