begin transaction;

INSERT INTO MOVIESTAR (NAME, GENDER, BIRTHDATE)
VALUES ('Nikole Kidman', 'F', 1967-06-20);

DELETE FROM MOVIEEXEC
WHERE NETWORTH < 10000000;

DELETE FROM MOVIESTAR
WHERE ADDRESS is NULL;

UPDATE MOVIEEXEC
SET NAME = 'Pres. ' + NAME
WHERE CERT# IN ( SELECT PRESC#
				 FROM STUDIO );

rollback transaction;
