SELECT NAME
FROM MOVIESTAR
WHERE GENDER = 'f' AND NAME IN ( SELECT NAME 
								 FROM MOVIEEXEC
								 WHERE NETWORTH > 10000000 );

SELECT NAME
FROM MOVIESTAR
WHERE NAME NOT IN ( SELECT NAME
					FROM MOVIEEXEC );