CREATE VIEW actresses
AS
	SELECT NAME, BIRTHDATE
	FROM MOVIESTAR
	WHERE GENDER = 'f';

GO

CREATE VIEW actressesMovies
AS
	SELECT MOVIESTAR.NAME, COUNT(STARSIN.MOVIETITLE) as MOVIE_COUNT
	FROM MOVIESTAR LEFT JOIN STARSIN ON MOVIESTAR.NAME = STARSIN.STARNAME
	WHERE GENDER = 'f'
	GROUP BY MOVIESTAR.NAME;

GO

SELECT *
FROM actresses;

SELECT *
FROM actressesMovies;

DROP VIEW actresses;
DROP VIEW actressesMovies;