SELECT STARSIN.STARNAME, COUNT(DISTINCT MOVIE.STUDIONAME)
FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE
GROUP BY STARSIN.STARNAME;

SELECT STARNAME
FROM STARSIN
WHERE MOVIEYEAR > 1990
GROUP BY STARNAME
HAVING COUNT(*) >= 3;