SELECT STARNAME
FROM STARSIN JOIN MOVIESTAR ON STARNAME = NAME
WHERE GENDER = 'f' AND MOVIETITLE = 'Terms of Endearment';

SELECT STARNAME
FROM STARSIN JOIN MOVIE ON MOVIETITLE = TITLE AND MOVIEYEAR = YEAR
WHERE STUDIONAME = 'MGM' AND YEAR = 1995;