SELECT DISTINCT COUNTRY
FROM CLASSES
WHERE NUMGUNS >= ALL ( SELECT NUMGUNS
					   FROM CLASSES );

SELECT NAME
FROM SHIPS
WHERE CLASS IN ( SELECT CLASS
				 FROM CLASSES
				 WHERE BORE = 16 );

SELECT BATTLE
FROM OUTCOMES
WHERE SHIP IN ( SELECT NAME
				FROM SHIPS
				WHERE CLASS = 'Kongo' );

SELECT CLASS
FROM CLASSES C1
WHERE NUMGUNS >= ALL ( SELECT NUMGUNS
					   FROM CLASSES C2
					   WHERE C1.BORE = C2.BORE );

SELECT NAME
FROM SHIPS
WHERE CLASS IN ( SELECT CLASS
				 FROM CLASSES C1
				 WHERE NUMGUNS >= ALL ( SELECT NUMGUNS
										FROM CLASSES C2
										WHERE C1.BORE = C2.BORE ) );