begin transaction;

INSERT INTO CLASSES
VALUES ('Nelson', 'bb', 'Gt.Britain', 9, 16, 34000);
INSERT INTO SHIPS
VALUES ('Nelson', 'Nelson', 1927);
INSERT INTO SHIPS
VALUES ('Rodney', 'Nelson', 1927);

DELETE FROM SHIPS
WHERE NAME IN ( SELECT SHIP
				FROM OUTCOMES
				WHERE RESULT = 'sunk' );

UPDATE CLASSES
SET BORE = BORE*2.54, DISPLACEMENT = DISPLACEMENT/1.1;

DELETE FROM CLASSES
WHERE CLASS IN ( SELECT CLASS
				 FROM SHIPS
				 GROUP BY CLASS
				 HAVING COUNT(*) < 3 );

UPDATE CLASSES
SET BORE = ( SELECT BORE
			 FROM CLASSES
			 WHERE CLASS = 'Bismarck' ), DISPLACEMENT = ( SELECT DISPLACEMENT
														  FROM CLASSES
														  WHERE CLASS = 'Bismarck' )
WHERE CLASS = 'Iowa';

rollback transaction;