begin transaction;

ALTER TABLE MOVIE
ADD CONSTRAINT uniqMovLen UNIQUE (LENGTH);

ALTER TABLE MOVIE
ADD CONSTRAINT stUniqMovLen UNIQUE (STUDIONAME, LENGTH);

ALTER TABLE MOVIE
DROP CONSTRAINT uniqMovLen;

ALTER TABLE MOVIE
DROP CONSTRAINT stUniqMovLen;

rollback transaction;