SELECT DISTINCT STUDIO.NAME, M.STARNAME
FROM STUDIO JOIN ( SELECT MOVIE.STUDIONAME, MOVIE.TITLE,  STARSIN.STARNAME
				   FROM MOVIE JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE ) M ON STUDIO.NAME = M.STUDIONAME
ORDER BY STUDIO.NAME;

SELECT DISTINCT MOVIEEXEC.NAME
FROM MOVIEEXEC JOIN ( SELECT MOVIE.PRODUCERC#, MOVIE.TITLE,  STARSIN.STARNAME
				      FROM MOVIE JOIN STARSIN ON MOVIE.TITLE = STARSIN.MOVIETITLE ) M ON MOVIEEXEC.CERT# = M.PRODUCERC#
WHERE M.STARNAME = 'Harrison Ford';

SELECT DISTINCT MOVIESTAR.NAME
FROM MOVIESTAR JOIN ( SELECT STARSIN.STARNAME
					  FROM STARSIN JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE
					  WHERE MOVIE.STUDIONAME = 'MGM' ) M ON MOVIESTAR.NAME = M.STARNAME
WHERE MOVIESTAR.GENDER = 'f';

SELECT MOVIEEXEC.NAME, MOVIE.TITLE
FROM MOVIEEXEC JOIN MOVIE ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
WHERE MOVIEEXEC.NAME IN ( SELECT MOVIEEXEC.NAME
						  FROM MOVIEEXEC JOIN MOVIE ON MOVIEEXEC.CERT# = MOVIE.PRODUCERC#
						  WHERE MOVIE.TITLE = 'Star Wars' );

SELECT MOVIE.TITLE, MOVIE.YEAR, MOVIEEXEC.NAME
FROM MOVIE LEFT JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#;

SELECT MOVIE.TITLE, MOVIE.YEAR, MOVIEEXEC.NAME, MOVIE.STUDIONAME, STUDIO.ADDRESS
FROM MOVIE LEFT JOIN MOVIEEXEC ON MOVIE.PRODUCERC# = MOVIEEXEC.CERT#
           LEFT JOIN STUDIO ON MOVIE.STUDIONAME = STUDIO.NAME;

SELECT STARSIN.STARNAME
FROM STARSIN LEFT JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE
WHERE MOVIE.TITLE IS NULL;