SELECT SHIPS.NAME, CLASSES.COUNTRY, CLASSES.NUMGUNS, SHIPS.LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS;

SELECT NAME
FROM SHIPS
WHERE NAME IN ( SELECT OUTCOMES.SHIP
				FROM OUTCOMES JOIN BATTLES ON OUTCOMES.BATTLE = BATTLES.NAME
				WHERE year(DATE) = '1942' );