SELECT SHIPS.NAME
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE DISPLACEMENT > 35000;

SELECT SHIPS.NAME, CLASSES.DISPLACEMENT, CLASSES.NUMGUNS
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.BATTLE = 'Guadalcanal';

SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bb'
INTERSECT
SELECT COUNTRY
FROM CLASSES
WHERE TYPE = 'bc';

SELECT DISTINCT O1.SHIP
FROM OUTCOMES O1 JOIN BATTLES B1 on O1.BATTLE = B1.NAME
JOIN OUTCOMES O2 ON O1.SHIP = O2.SHIP JOIN BATTLES B2 ON O2.BATTLE = B2.NAME
WHERE O1.RESULT = 'damaged' AND B1.DATE < B2.DATE;