SELECT COUNT(DISTINCT CLASS)
FROM CLASSES;

SELECT AVG(CLASSES.NUMGUNS)
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS;

SELECT CLASSES.CLASS, MIN(SHIPS.LAUNCHED), MAX(SHIPS.LAUNCHED)
FROM CLASSES JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
GROUP BY CLASSES.CLASS;

SELECT CLASSES.CLASS, COUNT(M.RESULT)
FROM CLASSES LEFT JOIN ( SELECT *
						 FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP) M ON CLASSES.CLASS = M.CLASS AND M.RESULT = 'sunk'
GROUP BY CLASSES.CLASS;

SELECT SHIPS.CLASS, COUNT (SHIPS.NAME)
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME = OUTCOMES.SHIP
WHERE OUTCOMES.RESULT = 'sunk' AND SHIPS.CLASS IN ( SELECT CLASS
													FROM SHIPS
													GROUP BY CLASS
													HAVING COUNT(*) > 4 )
GROUP BY CLASS;

SELECT COUNTRY, AVG(DISPLACEMENT)
FROM CLASSES
GROUP BY COUNTRY;