SELECT period, COUNT(*) AS number
FROM ( SELECT CASE
				WHEN YEAR(BIRTHDATE) < 1960 THEN 'Before 60s'
				WHEN YEAR(BIRTHDATE) >= 1960 AND YEAR(BIRTHDATE) < 1970 THEN '60s'
				WHEN YEAR(BIRTHDATE) >= 1970 AND YEAR(BIRTHDATE) < 1980 THEN '70s'
				WHEN YEAR(BIRTHDATE) >= 1980 THEN 'After 70s'
			  END AS period
	   FROM MOVIESTAR ) AS M
GROUP BY period;