SELECT OUTCOMES.BATTLE
FROM OUTCOMES JOIN SHIPS ON OUTCOMES.SHIP = SHIPS.NAME
			  JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE CLASSES.NUMGUNS < 9 
GROUP BY OUTCOMES.BATTLE
HAVING COUNT(*) >= 3 AND SUM( CASE WHEN OUTCOMES.RESULT = 'ok' THEN 1 ELSE 0 END ) >= 2;